language: go
sudo: false

os:
  - linux

go:
  - 1.11.x
  - master

matrix:
  fast_finish: true
  include:
    - go: 1.11.x
      env: GO111MODULE=on

after_success:
  - bash <(curl -s https://codecov.io/bash)
